name: 'tfupdate Github Actions by masutaka'
description: 'Runs tfupdate via Github Actions'
inputs:
  tfupdate_subcommand:
    description: 'Subcommand to execute'
    required: true
  tfupdate_path:
    description: 'A path provided to tfupdate'
    required: true
    default: '.'
  tfupdate_options:
    description: 'Options provided to tfupdate'
    required: false
    default: '-r'
  tfupdate_provider_name:
    description: 'A name of provider (used if `provider` is given as the subcommand)'
    required: false
  update_tfenv_version_files:
    description: 'Whether of not to update .terraform-version files (used if `terraform` is given as the subcommand)'
    default: false
    required: false
  github_token:
    description: 'Github Token'
    required: true
  pr_base_branch:
    description: 'The base branch of a Pull Request'
    required: false
  assignees:
    description: 'A comma-separated list (no spaces around the comma) of GitHub handles to assign to this pull request'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
