name: 'tfupdate Github Actions by masutaka'
description: 'Runs tfupdate via Github Actions'
inputs:
  tfupdate_subcommand:
    description: 'Subcommand to execute'
    required: true
  tfupdate_path:
    description: 'A path provided to tfupdate'
    required: false
    default: '.'
  tfupdate_options:
    description: 'Options provided to tfupdate'
    required: false
    default: '-r'
  tfupdate_provider_name:
    description: 'A name of provider (used if `provider` is given as the subcommand)'
    required: false
  update_tfenv_version_files:
    description: 'Whether of not to update .terraform-version files (used if `terraform` is given as the subcommand)'
    default: 'false'
    required: false
  update_tool_versions_files:
    description: 'Whether or not to update .tool-versions files (used if `terraform` is given as the subcommand)'
    default: 'false'
    required: false
  github_token:
    description: 'Github Token'
    required: true
  pr_base_branch:
    description: 'The base branch of a Pull Request'
    required: false
  assignees:
    description: 'A comma-separated list (no spaces around the comma) of GitHub handles to assign to this pull request'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install tfupdate
      env:
        TFUPDATE_VERSION: v0.9.3
        TFUPDATE_SHA256: dfdc45648bb5e3efd4fb6e6e03fb672254041640116e2255380b5dfe7c01ff3a
      run: |
        curl -fL --output "$RUNNER_TEMP/tfupdate.tar.gz" "https://github.com/minamijoyo/tfupdate/releases/download/${TFUPDATE_VERSION}/tfupdate_${TFUPDATE_VERSION#v}_linux_amd64.tar.gz"
        echo "${TFUPDATE_SHA256} $RUNNER_TEMP/tfupdate.tar.gz" | sha256sum -c -
        tar xz -C "$RUNNER_TEMP" -f "$RUNNER_TEMP/tfupdate.tar.gz" tfupdate
        echo "$RUNNER_TEMP" >> "$GITHUB_PATH"
        export PATH="$RUNNER_TEMP:$PATH"
        tfupdate --version
      shell: bash

    - name: Run entrypoint
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_TFUPDATE_SUBCOMMAND: ${{ inputs.tfupdate_subcommand }}
        INPUT_TFUPDATE_PATH: ${{ inputs.tfupdate_path }}
        INPUT_TFUPDATE_OPTIONS: ${{ inputs.tfupdate_options }}
        INPUT_TFUPDATE_PROVIDER_NAME: ${{ inputs.tfupdate_provider_name }}
        INPUT_UPDATE_TFENV_VERSION_FILES: ${{ inputs.update_tfenv_version_files }}
        INPUT_UPDATE_TOOL_VERSIONS_FILES: ${{ inputs.update_tool_versions_files }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_PR_BASE_BRANCH: ${{ inputs.pr_base_branch }}
        INPUT_ASSIGNEES: ${{ inputs.assignees }}
        GH_TOKEN: ${{ inputs.github_token }}
        GH_REPO: ${{ github.repository }}
